### ISSUE TITLE
`keyring.errors.KeyringLocked` is not caught and produces a traceback

### ISSUE THREAD

**Issue by mr-cal** [canonical/craft-store#166]
### Bug Description

`craft-store` does not catch `keyring.errors.KeyringLocked` and the user will get a traceback instead of a clean error.

The exception could be handled around [here](https://github.com/canonical/craft-store/blob/cafde972baeed23290ec4a2579b78cffe76368f7/craft_store/auth.py#L193).

### To Reproduce

This was originally produced by ssh'ing into an Ubuntu desktop VM.  Gnome-keyring tries to show the unlock request in the GUI (which isn't visible).

Another method:
1. On a machine with gnome-keyring, run `snapcraft login`
2. Lock the keyring
3. Run `snapcraft whoami`
4. Cancel the keyring unlock prompt

### Relevant log output

```shell
$ snapcraft whoami
Traceback (most recent call last):
File "/snap/snapcraft/10425/bin/snapcraft", line 8, in <module>
sys.exit(run())
File "/snap/snapcraft/10425/lib/python3.10/site-packages/snapcraft/cli.py", line 258, in run
_run_dispatcher(dispatcher, global_args)
File "/snap/snapcraft/10425/lib/python3.10/site-packages/snapcraft/cli.py", line 230, in _run_dispatcher
dispatcher.run()
File "/snap/snapcraft/10425/lib/python3.10/site-packages/craft_cli/dispatcher.py", line 487, in run
return self._loaded_command.run(self._parsed_command_args)
File "/snap/snapcraft/10425/lib/python3.10/site-packages/snapcraft/commands/account.py", line 257, in run
whoami = store.StoreClientCLI().store_client.whoami()
File "/snap/snapcraft/10425/lib/python3.10/site-packages/snapcraft/store/client.py", line 179, in _init_
self.store_client = get_client(ephemeral=ephemeral)
File "/snap/snapcraft/10425/lib/python3.10/site-packages/snapcraft/store/client.py", line 161, in get_client
client = craft_store.UbuntuOneStoreClient(
File "/snap/snapcraft/10425/lib/python3.10/site-packages/craft_store/ubuntu_one_store_client.py", line 47, in _init_
super().__init__(
File "/snap/snapcraft/10425/lib/python3.10/site-packages/craft_store/base_client.py", line 77, in _init_
self._auth = Auth(
File "/snap/snapcraft/10425/lib/python3.10/site-packages/craft_store/auth.py", line 192, in _init_
self._keyring.get_preferred_collection()
File "/snap/snapcraft/10425/lib/python3.10/site-packages/keyring/backends/SecretService.py", line 67, in get_preferred_collection
raise KeyringLocked("Failed to unlock the collection!")
keyring.errors.KeyringLocked: Failed to unlock the collection!
```

**Comment by lengau** [comment]
I'm not sure what behaviour you'd like out of this. I see three options, though there may be more:

1. Raise our own exception (I prefer this)
2. Fall back to a MemoryKeyring
3. Fall back to a FileKeyring

In #1, the application could then choose (hopefully with user input 🙂 ) to retry in ephemeral mode. I don't like #2 too much because it could hide issues we have connecting to the keyring, and I really don't like #3 because it does #2 but with potential of insecure side-effects on disk.

My preference would be for #1 and having the app retry, with a related feature request for the app to be able to pass a keyring instance in case multiple libraries want to talk to a keyring. 

![What do you think?](https://i.imgur.com/i7Ef9L0.gif)

What do you think?

**Comment by mr-cal** [comment]
I don't have a strong preference.  @sergiusens mentioned falling back to the file-based keyring.

It could be misleading to automatically switch to a memory or file-based keyring if a valid keyring can't be unlocked, so raising a craft-store exception (option #1) seems reasonable too.

**Comment by sergiusens** [comment]
Let’s only do step one, a bespoke exception is raised that we properly handle already everywhere, essentially

```python
try:
     <exception_raising_method>()
except <raisedException>:
    raise CraftStoreKeyringMissconfigurationError("text")
```
